Create wine price parsers
Nattalli/lteam-wine-map pull request #31
Opened 2023-03-25 16:07 UTC by antos07

2023-03-26 16:11 UTC, Nattalli requested changes
Overall - very good job

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/serializers.py
> +    max_price = serializers.FloatField()
in one shop can be two prices?

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/views.py
> +    WineInShopSerializer
better use `()` instead of `\`

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/views.py
> +        return Response(serializer.data)
add message, please

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/views.py
> +        return Response(serializer.data)
and status

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/parsers/silpo.py
> +from . import errors
how ir works?

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/parsers/silpo.py
> +    items = data.get("items")
`items` mean wines? If it is - better use `wines` variable name

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/parsers/utils.py
> +        return results
```suggestion
        return [result for result in results if result]
```

2023-03-26 16:11 UTC, Nattalli commented on backend/wine_map/parsers/utils.py
> +        return results
just because you use `results` variable name twice

2023-03-26 16:19 UTC, antos07 commented on backend/wine_map/serializers.py
> +    max_price = serializers.FloatField()
As I am parsing search results, I can't know which wine is the one I need

2023-03-26 16:21 UTC, antos07 commented on backend/wine_map/parsers/silpo.py
> +from . import errors
Just a relative import. It imports the module `errors` from the package `wine_map.parsers`

2023-03-27 15:35 UTC, Nattalli approved these changes

2023-03-27 16:27 UTC, Afformativ approved these changes

2023-03-27 16:33 UTC, merged