adding views
Nattalli/lteam-wine-map pull request #33
Opened 2023-03-26 14:59 UTC by romchik2612

2023-03-26 16:00 UTC, Nattalli commented on backend/wine_map/views.py
> +    return AccessToken(token_str)["user_id"]
oh, you find user id in this way. But you can just use `request.user`

2023-03-26 16:00 UTC, Nattalli commented on backend/wine_map/views.py
> +        return Response(serializer.data)
add permission classes here and everywhere

2023-04-02 13:19 UTC, antos07 requested changes
I think it could be better to organize endpoints like this:
- `GET /wine/favourites/` to list favourites
- `PUT /wine/favourites/` to put wine into the favourites
- `DELETE /wine/favourites/` to clear favourites
- `DELETE /wine/favourites/<wine_id>` to remove wine from favourites

2023-04-02 13:19 UTC, antos07 commented on backend/wine_map/views.py
> +            wine.in_favourites_of.add(user_id)
```suggestion
        user = request.user
        if user.favourite_wines.contains(wine):
            user.favourite_wines.remove(wine)
        else:
            user.favourite_wines.add(wine)
```

2023-04-02 13:19 UTC, antos07 commented on backend/wine_map/views.py
> +        wine = Wine.objects.get(pk=self.kwargs["wine_id"])
Add 404 response, when wine is not found

2023-04-02 13:39 UTC, romchik2612 commented
> I think it could be better to organize endpoints like this:
> 
> * `GET /wine/favourites/` to list favourites
> * `PUT /wine/favourites/` to put wine into the favourites
> * `DELETE /wine/favourites/` to clear favourites
> * `DELETE /wine/favourites/<wine_id>` to remove wine from favourites

don`t think so, it`s wine entity update - not separate endpoints, and one endpoint for add/remove wine is more comfortable for the front-end

2023-04-02 13:41 UTC, romchik2612 commented on backend/wine_map/views.py
> +            wine.in_favourites_of.remove(user_id)
we don`t have user favorite wines, only wine in favourite of

2023-04-02 13:41 UTC, romchik2612 commented on backend/wine_map/views.py
> +            wine.in_favourites_of.add(user_id)
we don`t have user favorite wines

2023-04-02 13:50 UTC, antos07 commented on backend/wine_map/views.py
> +            wine.in_favourites_of.add(user_id)
We do have))

Django creates a field in a related model. Check out the Wine model defenition - you'll see `in_favourites_of = models.ManyToManyField(get_user_model(), related_name="favourite_wines")`, which creates `favourite_wines` field in the User model

2023-04-02 16:44 UTC, Nattalli approved these changes

2023-04-02 16:50 UTC, antos07 approved these changes

2023-04-02 16:53 UTC, merged