Quiz backend
Nattalli/lteam-wine-map pull request #38
Opened 2023-04-02 16:53 UTC by antos07

2023-04-03 23:12 UTC, Afformativ approved these changes

2023-04-04 09:33 UTC, Nattalli requested changes

2023-04-04 09:33 UTC, Nattalli commented on backend/wine_map/models.py
> +    text = models.TextField(null=False, blank=False)
do we need `null=False, blank=False` here? Doesn't it a default value?

2023-04-04 09:33 UTC, Nattalli commented on backend/wine_map/urls.py
> +    path("questions/<int:pk>", QuizQuestionView.as_view(), name="quiz-question")
```suggestion
    path("questions/<int:pk>/", QuizQuestionView.as_view(), name="quiz-question")
```

2023-04-04 09:33 UTC, Nattalli commented on backend/wine_map/views.py
> +            question = queryset.filter(first=True).get()
why not:
```python
            question = queryset.get(first=True)
```

2023-04-04 09:48 UTC, Nattalli approved these changes

2023-04-04 09:48 UTC, merged