Set up
Nattalli/lteam-wine-map pull request #4
Opened 2023-02-26 09:47 UTC by Nattalli

2023-02-26 13:19 UTC, romchik2612 approved these changes

2023-02-26 21:17 UTC, antos07 requested changes

2023-02-26 21:17 UTC, antos07 commented on backend/config/settings.py
> +    "rest_framework",
Probably, it would be better to also add DRF into requirements.txt

2023-02-26 21:17 UTC, antos07 commented on README.md
> +`python3.9 -m venv venv`
It should be `python3.10`, not `python3.9`

2023-02-27 08:43 UTC, Nattalli commented on backend/config/settings.py
> +    "rest_framework",
oops, my bad

2023-02-27 08:44 UTC, Nattalli commented on README.md
> +`python3.9 -m venv venv`
agree

2023-02-27 09:59 UTC, antos07 approved these changes

2023-02-27 11:37 UTC, merged