final version of bot
Nattalli/lteam-wine-map pull request #44
Opened 2023-04-07 23:51 UTC by Afformativ

2023-04-09 19:29 UTC, Nattalli requested changes

2023-04-09 19:29 UTC, Nattalli commented on bot/main.py
> +def ask_question(update: Update, context: CallbackContext, user_id: int):
```suggestion
def ask_question(update: Update, context: CallbackContext, user_id: int) -> None:
```

2023-04-09 19:29 UTC, Nattalli commented on bot/main.py
> +    if context.user_data[user_id]["help_used"] is False:
```suggestion
    if not context.user_data[user_id]["help_used"]:
```

2023-04-09 19:29 UTC, Nattalli commented on bot/main.py
> +def answer_question(update: Update, context: CallbackContext):
```suggestion
def answer_question(update: Update, context: CallbackContext) -> None:
```

2023-04-09 19:29 UTC, Nattalli commented on bot/main.py
> +            "промокоду: PKDOS, який діє у всіх магазинах-партнерах. Щоб "
let's change promocode. For example, LWINE2023 would be better 😄

2023-04-09 19:29 UTC, Nattalli commented on bot/main.py
> +            "http://127.0.0.1:8000/🍷🔥"
can we make a link for our specific wine? We have a search by id in URL. Let's take a look what the link created our frontend developers. But it should be something like `'f"os.getenv("WEBSITE_LINK")'/wines/{wine.id}"`
(That is an example only)

2023-04-11 17:11 UTC, kseniia-grishchenko commented
what's the status? It would  be really nice to merge this already @Afformativ

2023-04-11 18:50 UTC, closed without merging