database set up
Nattalli/lteam-wine-map pull request #5
Opened 2023-02-26 15:32 UTC by romchik2612

2023-02-26 15:48 UTC, Nattalli approved these changes

2023-02-26 21:22 UTC, antos07 requested changes

2023-02-26 21:22 UTC, antos07 commented on .env.sample
> +DB_PASSWORD=cPj0ayCvwHTPtHYDzAC-U0DW6I38orjP
It isn't a good idea to put real credentials into the repository

2023-02-26 21:25 UTC, romchik2612 commented on .env.sample
> +DB_PASSWORD=cPj0ayCvwHTPtHYDzAC-U0DW6I38orjP
agree, but don`t think we can put them somewhere else now

2023-02-26 21:30 UTC, antos07 commented on .env.sample
> +DB_PASSWORD=cPj0ayCvwHTPtHYDzAC-U0DW6I38orjP
Our telegram group would be a better place, I guess (safer at least)

2023-02-27 08:34 UTC, Nattalli commented on .env.sample
> +DB_PASSWORD=cPj0ayCvwHTPtHYDzAC-U0DW6I38orjP
Agree, in the `.env.sample` should be fake data that shows what should be added to the `.env` file

2023-02-27 08:35 UTC, Nattalli commented on .env.sample
> +DB_PASSWORD=cPj0ayCvwHTPtHYDzAC-U0DW6I38orjP
if it is real data - we should replace it with fake data and separate it to the telegram or Google Sheets, etc.

2023-02-27 18:08 UTC, Nattalli approved these changes

2023-02-27 18:14 UTC, antos07 approved these changes

2023-03-03 21:51 UTC, merged