adding auth
Nattalli/lteam-wine-map pull request #8
Opened 2023-03-06 17:47 UTC by romchik2612

2023-03-06 18:17 UTC, Nattalli requested changes
Good job but left some comments. Also, let's use `""` everywhere? To have one codestyle

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/serializers.py
> +        model = User
make the following import:
```
from django.contrib.auth import get_user_model
```
and everywhere use `get_user_model()` instead of `User`. Not a big problem but best practice

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/serializers.py
> +        user = User.objects.create(
the same here, use `get_user_model()`

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/serializers.py
> +            username=validated_data['email'],
```suggestion
            username=validated_data['username'],
```

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/serializers.py
> +            username=validated_data['email'],
oh, we have no `username`. Maybe it's better to remove it?

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/serializers.py
> +        return user
and add a blank line in the end of the file

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/urls.py
> +]
add a blank line in the end of the file

2023-03-06 18:17 UTC, Nattalli commented on backend/authentication/views.py
> +
remove extra blank line

2023-03-06 18:18 UTC, Nattalli commented on backend/authentication/views.py
> +
> Good job but left some comments. Also, let's use `""` everywhere? To have one codestyle

oh, you've already made it! Awesome!

2023-03-06 18:21 UTC, romchik2612 commented on backend/authentication/serializers.py
> +            username=validated_data['email'],
> oh, we have no `username`. Maybe it's better to remove it?

i`m afraid that username is required identifier

2023-03-06 20:11 UTC, antos07 requested changes

2023-03-06 20:11 UTC, antos07 commented on backend/config/urls.py
>  ]
Add a blank line at the end of the file (recommended by PEP-8)

2023-03-11 08:05 UTC, antos07 approved these changes

2023-03-11 08:08 UTC, Nattalli approved these changes

2023-03-11 08:12 UTC, merged